name: Testitnow
favicon: null
layout_spectrum: 0.40839652181603014
typography_spectrum: 0.3260210033040494
title: This is the title
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d5d7d0'
    - '#010101'
    - '#978d83'
    - '#6d6255'
    - '#0083c1'
  brandStrength: 0.24010280729271472
  lightness: 0.039440486347302794
  saturation: 0.9657238826621324
  rhythmicContrast: 0.8252592026256025
purpose: []
